version: '3.1'

services:
  web:
    restart: always
    image: go-mysql-crud
    ports:
      - 10000:10000
    links:
      - mysql
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "DB_NAME=goblog"
      - "DB_PASS=Mysqlroot123"

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - /mysql:/var/lib/mysql